### ISSUE TITLE
Logos de los dojos no cargando correctamente [eOS Hera + Firefox]

### ISSUE THREAD

**Issue by LagrangianLad** [CoderDojoES/coderdojoes.github.io#6]
Buenos días. Solo por curiosear un poco me he metido a la página de los dojos y en la [sección en la que se muestran cada uno de los dojos del país](https://www.coderdojo.es/dojos/), he notado que **algunos de los logos no cargan como deberían**
![Screenshot from 2020-09-14 11-04-51](https://user-images.githubusercontent.com/63709477/93066847-b917a900-f67a-11ea-92a5-ea106fa318ff.png)
Si inspeccionamos el elemento, podemos ver que cada una de las imagenes esta dentro de una etiqueta `div`con clases de bootstrap y esta contiene a su vez una clase `dojo`. Es decir, `div .dojo`. Cada clase `dojo` contiene a su vez una etiqueta de imagen que pertenece a la clase `img-fluid` y que contiene el src de la imagen; que si no me equivoco es donde se encuentra el problema.
![Screenshot from 2020-09-14 11-06-25](https://user-images.githubusercontent.com/63709477/93067283-51159280-f67b-11ea-8f1b-dea6ad7b13d3.png)
Lo más probable es que como las imagenes que estas usando para mostrar los logotipos de los logos pertenecen a una URL externa a tu página y no están guardadas en la carpeta local **hayan cambiado de sitio en la URL ergo HTML no las puede abrir con el enlace que le pasas en el src**. Te recomiendo que revises si la posición de estas imagenes ha cambiado, cambiando así la URL para mostrarlas en HTML.
###### En caso de que te sirva, trabajo bajo el navegador Firefox y con Elementary OS Hera como sistema operativo.
Un saludo!

**Comment by migueabellan** [comment]
Hola Pablo, muchas gracias por el aviso .

El problema ha sido como bien comentas, fallo al cargar la URL, de modo que estábamos cargando las URLs desde el perfil de twitter, y si se cambia la imagen, se pierde el enlace. 

Se ha solucionado descargando las imágenes para enlazarlas directamente desde la web como puedes ver aquí: https://github.com/CoderDojoES/coderdojoes.github.io/commit/ae4e877df29517a67387dfbe944bd07426579aab

Muchas gracias por habernos avisado :100:
